#!/bin/env python3

from os import getenv, path
from datetime import datetime
from wand.image import Image
import sys

## Handle Command Line Stuff
debug = False

inList = []
nautilusList = getenv('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS','').splitlines()
if len(nautilusList) > 0 :
    if debug:
        print("Nautilus mode")
        print(len(nautilusList))

    inList = nautilusList[0:]

elif len(sys.argv) > 1:
    if debug:
        print("command line")
    inList = sys.argv[1:]

else:
    print("no files given, exiting...")
    exit(0)

inList.sort()
types = { 	".svg": True,
            ".png": True,
			".gif": True,
			".heic": True,
			".webp": True}
files = []
for f in inList:
	if path.splitext(f)[1].lower() in types:
		files.append(f)
	else:
		continue

if len(files) < 1:
	exit(0)
			

## Do the magic
for f in files:
	outFile = path.splitext(f)[0] + ".jpg"
	with Image(filename=f) as img:
		with img.clone() as converted:
			converted.format = 'jpg'
			overWrite = open(outFile, "wb")
			converted.save(overWrite)
			overWrite.close()
				
			
