#!/bin/env python3

from os import getenv, path, system, remove
from datetime import datetime
from wand.image import Image
import sys
import tempfile

debug = False

types = {	".jpeg": True,
			".jpg": True, 	
			".png": True,
			".gif": True,
			".heic": True,
			".webp": True}

now = datetime.now()


inList = []
nautilusList = getenv('NAUTILUS_SCRIPT_SELECTED_FILE_PATHS','').splitlines()

if len(nautilusList) > 0 :
    if debug:
        print("Nautilus mode")
        print(len(nautilusList))
    
    inList = nautilusList[0:]

elif len(sys.argv) > 1:
    if debug:
        print("command line")
    inList = sys.argv[1:]

else:
    print("no files given, exiting...")
    exit(0)

files = []
for f in inList:
	if path.splitext(f)[1].lower() in types:
		files.append(f)
	else:
		continue

if len(files) < 1:
	exit(0)
			

for f in files:

    with tempfile.TemporaryDirectory(suffix=None, prefix=None, dir=None, ignore_cleanup_errors=False) as workDir:
        inFile = "'" + f + "'"
        outFile = path.dirname(f) + "/"
        if outFile == "/":
            outFile = ""
        if debug:
            print("OUTFILE is:  " + outFile)

        outFile = outFile + path.splitext(path.basename(f))[0].replace(" ","")
        outFile = outFile + ".png"

        if path.isfile(outFile):
            outFile = path.splitext(outFile)[0] + now.strftime("%m-%d_%H-%M-%S.png")

        masterMaskBefore = workDir + "/before_" + now.strftime("a_%M-%S.gif")
        masterMaskAfter = workDir + "/after_" + now.strftime("z_%M-%S.gif")

        cmd = "convert " + inFile
        cmd = cmd + " \( -clone 0 -negate -threshold 1% -type bilevel +write " + masterMaskBefore 
        cmd = cmd + " -define connected-components:area-threshold=30 -define connected-components:mean-color=true -connected-components 4 +write " + masterMaskAfter
        cmd = cmd + " \) -alpha off -compose copy_opacity -composite " + outFile
        

        if debug:
            print(cmd)
        system(cmd)
        
