#!/bin/env python3

from os import getenv
from pathlib import Path
from wand.image import Image
import sys


if sys.stdin.isatty():
    inList = sys.argv[1:].copy()
else:
    # Running from nautilus
    inList = getenv("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS", "").splitlines()

inList.sort()
files = []
allowed_extensions = [".pdf", ".png", ".jpg", ".jpeg", ".gif", ".heic", ".webp"]
for f in inList:
    file = Path(f)
    if file.suffix in allowed_extensions and file.exists():
        files.append(file)


if len(files) < 1:
    print(
        f"No files given. this script only allows files of types: {', '.join(allowed_extensions)}"
    )
    exit(0)

## Do the magic
for f in files:
    fname = f.name.rsplit('.')[0]
    out_file = f.with_name(fname + '_rotated' + f.suffix)

    with Image(filename=f) as img:
        if len(img.sequence) > 1:
            with img.clone() as rotated:
                for img_frame in rotated.sequence:
                    with img_frame as frame:
                        frame.rotate(90)
                new_file = open(out_file, "wb")
                rotated.save(new_file)
                new_file.close()
        else:
            with img.clone() as rotated:
                rotated.rotate(90)
                new_file = open(out_file, "wb")
                rotated.save(new_file)
                new_file.close()
