#!/bin/env python3

from os import getenv
from pathlib import Path
from pypdf import PdfReader, PdfWriter
from sys import stdin, argv, version


def collect_files(allowed_extensions):
    """Collect files selected in nautilus or passed by the command line.
    Checks if files exist and are of the correct type(by file extension).
    Returns a list of Path() objects.
    Exits early if the files are invalid / non-existent.
    needs the following imports...
    from sys import stdin, argv"""

    if stdin.isatty():
        inList = argv[1:].copy()
    else:
        inList = getenv("NAUTILUS_SCRIPT_SELECTED_FILE_PATHS", "").splitlines()

    inList.sort()
    files = []
    for f in inList:
        file = Path(f)
        if file.suffix in allowed_extensions and file.exists():
            files.append(file)

    if len(files) < 1:
        print(
            "No files given. this script only allows files of types: ",
            f"'{', '.join(allowed_extensions)}",
        )
        exit(0)
    else:
        return files


def gen_new_name(f, suffix='', ext=''):
    """Take a pathlib.Path() object and optional suffix and/or extension.
    return a new name with the suffix and/or extension added."""

    fname = f.name.rsplit(".")[0]
    ex = ext if ext else f.suffix

    return f.with_name(fname + suffix + ex)


def rotate_pdf(f):

    output = gen_new_name(f, suffix='_rotated')
    reader = PdfReader(f)
    writer = PdfWriter()

    for page in reader.pages:
        writer.add_page(page.rotate(90))

    with open(output, 'wb') as fp:
        writer.write(fp)


def process_files(files):
    """Takes a list of pathlib.Path() objects and does some processing (image / effects) on the files."""
    v = version.rsplit(" ")[0]
    v = [int(x) for x in v.split(".")]

    if v[0] >= 3 and v[1] >= 12:
        from concurrent.futures import ProcessPoolExecutor

        with ProcessPoolExecutor() as executor:
            executor.map(rotate_pdf, files)
    else:
        for f in files:
            rotate_pdf(f)


if __name__ == "__main__":
    allowed_extensions = [
        ".pdf",
    ]
    files = collect_files(allowed_extensions)
    process_files(files)
